FROM ubuntu:latest

WORKDIR /

ADD unpub/unpub.exe /unpub

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait

RUN chmod a+x /wait

EXPOSE 4000

CMD /wait && /unpub -d $DB_URL