FROM ubuntu:latest

WORKDIR /

ADD unpub/unpub.exe /unpub

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait

RUN chmod a+x /wait

EXPOSE $UNPUB_PORT

CMD /wait && /unpub -p $UNPUB_PORT -d $UNPUB_DB_URL -f $UNPUB_FILE_STORE_PATH